### ISSUE TITLE
[Bug]: GCC output clang keywords

### ISSUE THREAD

**Issue by 428571c** [termux-user-repository/tur#1067] opened 2024-06-07 05:06 UTC
### Problem description

I compiled a very simple C program using gcc, but when I cat it, I found the keyword "clang". This is a problem. I hate Clang's BSD license and his junk architecture.
```c
#include <stdio.h>
int main(){
    printf("Hello World!");
    return 0;
}
```
```
������o`���o���oN���o@@@@��8P�p�`�Android (10552028, +pgo, +bolt, +lto, -mlgo, based on r487747d) clang version 17.0.2 (https://android.googlesource.com/toolchain/llvm-project d9f89f4d16663d5012e5c09495f3b30ece3d2362)GCC: (GNU) 9.5.08P�8�`  �
�
```

### What steps will reproduce the bug?

~ $ cat /sdcard/test.c
#include <stdio.h>
int main(){
    printf("Hello World!");
    return 0;
}
~ $ clang
The program clang is not installed. Install it by executing:
 pkg install clang
~ $ gcc --version
gcc (GCC) 9.5.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
~ $ gcc -o test /sdcard/test.c
~ $ cat test

Then I discovered this paragraph.
```
������o`���o���oN���o@@@@��8P�p�`�Android (10552028, +pgo, +bolt, +lto, -mlgo, based on r487747d) clang version 17.0.2 (https://android.googlesource.com/toolchain/llvm-project d9f89f4d16663d5012e5c09495f3b30ece3d2362)GCC: (GNU) 9.5.08P�8�`  �
�
```

### What is the expected behavior?

This is not what should be. Gcc does not use clang as the backend. I compile the same code in the genuine GCC version of Arch Linux, and the keyword "clang" will not appear.
```
��(GCC: (GNU) 14.1.1 202405078Tx���P    �
```

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=6146
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.ustc.edu.cn/termux/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
gcc-default-9/tur-packages 0.3-1 all [upgradable from: 0.3]
proot-distro/stable 4.14.0 all [upgradable from: 4.13.0-1]
termux-tools version:
1.42.2
Android version:
13
Kernel build information:
Linux localhost 5.10.149 #1 SMP PREEMPT Wed Sep 27 04:17:39 UTC 2023 aarch64 Android
Device manufacturer:
Android
Device model:
Android
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by licy183** [comment] 2024-06-07 13:15
This is not a bug. `crtbegin_dynamic.o` and `crtend_android.o` are shipped with NDK toolchain, and they are compiled with clang.

This cannot be fixed on our side.

**Closed by licy183** 2024-06-07 13:15 UTC
Labels: invalid
