### ISSUE TITLE
Can't execute Codon

### ISSUE THREAD

**Issue by Lufims** [termux-user-repository/tur#1055] opened 2024-05-29 18:48 UTC
### Problem description

I installed Codon and I can't execute it to run a script

### What steps will reproduce the bug?

Install codon and use `codon run -release <script>`

### What is the expected behavior?

Execute the script with codon 

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~mBKhLOOh0TmY7A9HfS_XcQ==/com.termux-ZwBSGCpIRiHN1StfGovIKQ==/base.apk
TERMUX_APP__APK_RELEASE=UNKNOWN
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=false
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=11562
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c98,c258,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c98,c258,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10610
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.42.1
Android version:
14
Kernel build information:
Linux localhost 4.19.191-27956322-abA137FXXS4DXC1 #1 SMP PREEMPT Mon Mar 11 16:57:40 +07 2024 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A137F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
```

**Comment by licy183** [comment] 2024-05-30 03:40
I can't reproduce it on my devide.

**Comment by Lufims** [comment] 2024-05-30 12:13
I forgot to say, the output is command not found

**Comment by licy183** [comment] 2024-05-30 12:16
`codon` doesn't support 32-bit arches like arm. This cannot be fixed on our side.

**Closed by licy183** 2024-05-30 12:16 UTC
Labels: not bug
