### ISSUE TITLE
[Bug]: code-server unable to install most extensions

### ISSUE THREAD

**Issue by Merith-TK** [termux-user-repository/tur#523] opened 2023-08-05 00:30 UTC
### Problem description

the `code-server` package is unable to install most extensions as they are not "supported in code-server for Web" despite my other code-server instances, which use Release Tarballs from [cdr/code-server](https://github.com/coder/code-server), able to install the extensions without issue

### What steps will reproduce the bug?

screenshot taken from `tur/code-server`
![image](https://github.com/termux-user-repository/tur/assets/10422110/e33d2cda-8c7e-4651-af7f-1b64db98fc3a)

### What is the expected behavior?

screenshot taken from release tarball, launched with [code-server-mc](https://modrinth.com/mod/code-server)
![image](https://github.com/termux-user-repository/tur/assets/10422110/1ec6a6ca-871a-4710-96d3-14ae0548bfb8)

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=9622
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.bardia.tech/termux/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
13
Kernel build information:
Linux localhost 4.14.113-25950142 #1 SMP PREEMPT Tue Jun 20 20:35:13 KST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G715U1
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.api versionCode:51
com.termux.boot versionCode:7
com.termux.tasker versionCode:6

```

**Comment by licy183** [comment] 2023-08-05 06:04
Not a bug. See https://github.com/termux-user-repository/tur/issues/399#issuecomment-1554796798

**Comment by licy183** [comment] 2023-08-10 10:28
I don't think this can be fixed in our side, so I'd like to close this issue. For more information, see https://coder.com/docs/code-server/latest/termux#many-extensions-including-language-packs-fail-to-install.

**Closed by licy183** 2023-08-10 10:28 UTC
Labels: not bug
