### ISSUE TITLE
[Bug]: Chromium : Crash when entering the Google Login page

### ISSUE THREAD

**Issue by hansm629** [termux-user-repository/tur#1182] opened 2024-09-08 15:04 UTC
### Problem description

When you enter the `Google Login page`
Chromium browser is crashed.

The interesting thing is that there is no problem if it is a guest mode.

`llvmpipe`, `virpipe`, `zink`, and `kgsl` all have the same symptoms.

Chromium Ver :  125.0.6422.141

### What steps will reproduce the bug?

Symptoms occur when you enter the Google Login page.

The error below is coming out.

```
[0908/235131.128511:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0908/235131.128990:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0908/235131.130112:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0908/235131.130317:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0908/235131.131777:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0908/235131.131851:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0908/235131.132030:ERROR:elf_dynamic_array_reader.h(64)] tag not found
Segmentation fault
``` 

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=15600
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.qvq.net.cn/termux/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.qvq.net.cn/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.43.4
Android version:
14
Kernel build information:
Linux localhost 5.15.123-android13-8-28577532-abX916NKOS4BXG5 #1 SMP PREEMPT Thu Jul 11 04:25:20 UTC 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-X916N
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.x11 versionCode:14
com.termux.api versionCode:51
```

**Comment by licy183** [comment] 2024-09-09 05:55
I don't have enough time to debug chromium-related apps these days. I'll mark this as help wanted.

**Comment by hansm629** [comment] 2024-09-09 13:18
@kcubeterm
Could you please help me?

**Comment by EDLLT** [comment] 2024-09-12 20:47
> @kcubeterm
> Could you please help me?

I faced a similar issue with chromium as well when I had applications dependent on the browser for logging in and redirecting back to the applicaton. The best solution in my case was to use Firefox instead

**Comment by jorbig** [comment] 2024-09-14 20:34
Same problem here. The crash only doesn't occur on Google login pages when browsing as a Guest...

**Comment by hansm629** [comment] 2024-10-01 15:36
@knyipab 
Sir, hello. Could you possibly build the latest version of the Chromium browser? 
I would appreciate it.

**Comment by hansm629** [comment] 2024-10-03 06:16
@knyipab 
Thank you for your response.
This may not be related to the current issue, but when do you expect the release of LibreOffice?

I'm personally looking forward to it.

**Comment by shiumano** [comment] 2024-10-04 06:33
The crash occurs on the Discord login page as well as on the Google login page.
This problem is probably a compatibility issue between Chromium itself and Termux.
I have tried running Chromium's deb package for Ubuntu and Thorium, and it crashes under the same conditions.

**Comment by shiumano** [comment] 2024-10-04 06:38
I don't think it matters much, but I ran it in Wayland (Weston) just in case.
It crashed normally.

**Comment by licy183** [comment] 2024-10-04 14:33
Chromium in Termux doesn't have feature libudev enabled, but accessing Google Login page in chromium checks HID Service which needs libudev to work properly.

In both Termux and Proot envs, libudev will not work properly because neither of them have systemd support. Maybe some wrappers of libudev (such as https://github.com/therealkenc/libudev-stub) will make chromium in proot work.

**Comment by licy183** [comment] 2024-10-05 15:10
Should be fixed by https://github.com/termux-user-repository/chromium-builder/pull/32.

It will take about a day to build chromium using GitHub Action...

**Comment by hansm629** [comment] 2024-10-12 16:48
@licy183 
When will the pull request be completed~?

I’m anxiously waiting~ :)

**Comment by licy183** [comment] 2024-10-14 12:13
Ahhh... My vacation is over and I am still doing my internship. I don’t have enough network traffic to download chromium's source code.

**Comment by jorbig** [comment] 2024-10-14 12:50
Hope someone (else) will pull this off in the near future!

**Comment by EDLLT** [comment] 2024-10-14 13:39
@hansm629 

Question, why do you bother using chromium within termux rather than the native android apps?
Or if you want a browser with extension support, then kiwi browser(FOSS) is also an option

I personally only use the browsers within termux if some site is causing trouble on the native android apps

**Comment by hansm629** [comment] 2024-10-14 14:10
@EDLLT 
A browser that runs in the Termux XFCE4 computing environment is what really matters; an Android browser itself doesn't have any significance.

Switching from using Termux XFCE4 back to the Android home screen to launch a browser? That doesn't fit usability at all.

**Comment by shiumano** [comment] 2024-10-14 19:10
@EDLLT 
If you have access to a keyboard and mouse, there's no better option than Termux:X11.
Also, wouldn't it be nice to have developer tools in a split or separate window?

**Comment by nscreated** [comment] 2024-11-23 18:22
My reason for wanting Chromium is that saving webpages as PWAs is a pretty good substitute for having a more robust app repository on Termux.

**Closed** 2024-11-25 15:18 UTC
Labels: bug, help wanted

**Comment by jorbig** [comment] 2024-11-25 15:51
@nscreated you don't need to reinstall. Just do ```pkg update && pkg upgrade -y```
I just did and the issue is solved! Thank you so much @licy183

**Comment by nscreated** [comment] 2024-11-25 16:18
> @nscreated you don't need to reinstall. Just do `pkg update && pkg upgrade -y` I just did and the issue is solved! Thank you so much @licy183

Oh right. Yes, after doing that, I am allllll goooood.

**Comment by nathanh18** [comment] 2025-05-01 11:53
> [@nscreated](https://github.com/nscreated) you don't need to reinstall. Just do `pkg update && pkg upgrade -y` I just did and the issue is solved! Thank you so much [@licy183](https://github.com/licy183)

What about proot ubuntu 24.04 how do I pick up this fix? Currently using repo ppa:xtradeb/apps for chromium and I see this issue.

**Comment by licy183** [comment] 2025-05-01 13:29
Installing a libudev stub library should fix this. Try to compile https://github.com/therealkenc/libudev-stub or https://github.com/illiliti/libudev-zero and put it under `/lib64/aarch64-linux-gnu/`.

**Comment by nathanh18** [comment] 2025-05-01 14:24
> Installing a libudev stub library should fix this. Try to compile https://github.com/therealkenc/libudev-stub or https://github.com/illiliti/libudev-zero and put it under `/lib64/aarch64-linux-gnu/`.

Thanks it worked.
